---
hero_image: images/banner.png
title: Răsărit de soare
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Creează un răsărit de soare animat.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introducere
  completion: engaged
- title: Creează soarele
- title: Animează răsăritul de soare
- title: 'Provocare: Animație în diagonală'
- title: Animație infinită
- title: Animează cerul
- title: 'Provocare: Perfecționează cerul'
  completion: internal
- title: 'Provocare: Mai multă animație'
