---
hero_image: images/banner.png
title: Nascer do Sol
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Crie um nascer do sol animado.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Introdução
- title: Criando o sol
- title: Animando o nascer do sol
  completion:
  - engaged
- title: 'Desafio: Animação diagonal'
- title: Repetição da animação
- title: Animando o céu
  completion:
  - internal
- title: 'Desafio: Melhorar o céu'
- title: 'Desafio: Mais animações'
