---
hero_image: images/banner.png
title: Sunrise
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Create an animated sunrise.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Robot parlanchín
  - 
    title: Creating the sun
  - 
    title: Animating the sunrise
  - 
    title: 'Challenge: Diagonal animation'
  - 
    title: Infinite animation
  - 
    title: Animating the sky
  - 
    title: 'Challenge: Improve the sky'
  - 
    title: 'Challenge: More animation'
