---
hero_image: images/banner.png
title: Wschód słońca
theme: żółty
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, projekt-1, programowanie-0, obliczenia-fizyczne-0, produkcja-0, społeczność-0
description: Stwórz animację ze wschodem słońca.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Tworzenie animacji słońca
  - 
    title: Animacja wschodzącego słońca
  - 
    title: 'Wyzwanie: Animacja po przekątnej'
  - 
    title: Niekończąca się animacja
  - 
    title: Tworzenie animacji nieba
  - 
    title: 'Wyzwanie: Popraw niebo'
  - 
    title: 'Wyzwanie: Więcej animacji'
