---
hero_image: images / banner.png
title: Sunrise
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Stwórz animację ze wschodem słońca.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: projekty
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Stworzenie słońca
  - 
    title: Animacja wschodzącego słońca
  - 
    title: 'Wyzwanie: Animacja po przekątnej'
  - 
    title: Niekończąca się animacja
  - 
    title: Tworzenie animacji nieba
  - 
    title: 'Wyzwanie: Popraw niebo'
  - 
    title: 'Wyzwanie: Więcej animacji'
