---
hero_image: images/banner.png
title: Izlazak sunca
theme: yellow
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Kreiraj animirani izlazak sunca.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Kreiranje sunca
- title: Animacija izlaska sunca
  completion:
  - engaged
- title: 'Izazov: Dijagonalna animacija'
- title: Neprekidna animacija
- title: Animacija neba
  completion:
  - internal
- title: 'Izazov: Poboljšaj nebo'
- title: 'Izazov: Više animacije'
