---
hero_image: images/banner.png
title: Lever de Soleil
theme: jaune
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
description: Créer un lever de soleil animé.
original_url: https://codeclubprojects.org/en-GB/webdev/sunrise
interests: ''
technologies: html-css-javascript
site_areas: projets
hardware: ''
software: html-css-javascript
version: 3
last_tested: 2017-01-01
steps:
  - title: Introduction
  - title: Créer le soleil
  - title: Animer le lever de soleil
  - title: 'Défi : Animation diagonale'
  - title: Animation infinie
  - title: Animer le ciel
  - title: 'Défi : Améliorer le ciel'
  - title: "Défi : Plus d'animations"
